[package]
name = "log4cplus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.136"
libc = "0.2.169"

[build-dependencies]
conan2 = "0.1"
cxx-build = "1.0.136"
