[package]
name = "log-log4cplus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4cplus = { path = "../log4cplus" }

[dev-dependencies]
rand = "0.8.5"
